WebLabApp.web/Models/EmailModel.cs
namespace WebLabApp.Web.Models
{
    public class EmailModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string MessageText { get; set; }
    }
}

WebLabApp.web/Models/ErrorViewModel.cs
namespace WebLabApp.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebLabApp.web/Models/LanguageSelectionModel.cs
namespace WebLabApp.web.Models
{
    public class LanguageSelectionModel
    {
        public string[] AvailableCultures { get; set; }
        public string CurrentCulture { get; set; }
    }
}

WebLabApp.web/Models/ValidationModel.cs
namespace WebLabApp.web.Models
{
    public class ValidationModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int? Age { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public decimal? Salary { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
    }
}

WebLabApp.web/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebLabApp.Web.Controllers
{
	public class FileController : Controller
	{
		private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;
		public FileController(Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
		{
			_hostingEnvironment = hostingEnvironment;
		}
		[HttpGet]
		public IActionResult Index()
		{
			var filesPath = Path.Combine(_hostingEnvironment.WebRootPath, "files");
			var files = Directory.GetFiles(filesPath).Select(Path.GetFileName).ToList();
			return View(files);
		}
		[HttpPost]
		public async Task<IActionResult> Index(IFormFile Upload)
		{
			if (Upload != null)
			{
				var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "files", Upload.FileName);

				using (var stream = System.IO.File.Create(filePath))
				{
					await Upload.CopyToAsync(stream);
				}
			}

			var filesPath = Path.Combine(_hostingEnvironment.WebRootPath, "files");
			var files = Directory.GetFiles(filesPath).Select(Path.GetFileName).ToList();
			return View(files);
		}
	}
}

WebLabApp.web/Controllers/HomeController.cs
using WebAppLab.Services.EmailServices;
using WebLabApp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Diagnostics;
using System.Resources;
using WebLabApp.web.Models;

namespace WebLabApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
		private readonly ISender _emailSender;
        private readonly IStringLocalizer<HomeController> _localizer;
        public HomeController(ILogger<HomeController> logger, ISender emailSender, IStringLocalizer<HomeController> localizer)
		{
			_logger = logger;
			_emailSender=emailSender;
            _localizer = localizer;
        }
        public IActionResult Index()
        {
            var model = new LanguageSelectionModel
            {
                AvailableCultures = new[] { "en-US", "uk-UA" }, // Add other cultures if needed
                CurrentCulture = System.Globalization.CultureInfo.CurrentCulture.Name
            };

            return View(model);
        }
        [HttpPost]
		public async Task<IActionResult> SendEmail([FromBody] EmailModel vm)
		{
			var _vm = vm;
			if (_vm == null)
			{
				return BadRequest();
			}
			await _emailSender.SendEmailAsync(_vm.Email, "Test", _vm.MessageText);
			return Ok();
		}
		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult LanguagePartial()
        {
            var model = new List<string> { "en", "uk" };
            return PartialView("_LanguageSwitcher", model);
        }
    }
}

WebLabApp.web/Controllers/ValidatorController.cs
using Microsoft.AspNetCore.Mvc;
using WebLabApp.web.Models;

namespace WebLabApp.web.Controllers
{
    public class ValidatorController : Controller
    {
        public IActionResult Validator()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return RedirectToAction("Validator");
        }
    }
}

WebLabApp.web/Views/Shared/Components/Navbar/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebLabApp.web.Views.Shared.Components.Navbar
{
    public class NavbarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebLabApp.web/Views/File/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>File Upload and Download</title>
</head>
<body>

    <section class="container mt-5">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h1>Upload Files</h1>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="fileUpload">Choose File</label>
                        <input type="file" class="form-control-file" id="fileUpload" name="Upload">
                    </div>
                    <button type="submit" class="btn btn-success">Upload</button>
                </form>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header bg-info text-white">
                <h1>Download Files</h1>
            </div>
            <div class="card-body">
                @foreach (var file in Model)
                {
                    <a href="/Files/@file" download="@file" class="btn btn-primary mr-2 mb-2">@file</a>
                }
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

WebLabApp.web/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using WebLabApp.web.Models;

@inject IViewLocalizer Localizer

@model LanguageSelectionModel;

@{
    ViewData["Title"] = Localizer["Title"];
    string currentCulture = System.Globalization.CultureInfo.CurrentCulture.Name;
}
<!-- Mashead header-->
<header class="masthead">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <!-- Mashead text and app badges-->
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
                    <h1 class="display-1 lh-1 mb-3">@Localizer["ShowcaseYourApp"]</h1>
                    <p class="lead fw-normal text-muted mb-5">@Localizer["LaunchLandingPage"]</p>
                    <div class="d-flex flex-column flex-lg-row align-items-center">
                        <a class="me-lg-3 mb-4 mb-lg-0" href="#!"><img class="app-badge" src="assets/img/google-play-badge.svg" alt="..." /></a>
                        <a href="#!"><img class="app-badge" src="assets/img/app-store-badge.svg" alt="..." /></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Masthead device mockup feature-->
                <div class="masthead-device-mockup">
                  

                  
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Quote/testimonial aside-->

<!-- App features section-->
<section id="features">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-8 order-lg-1 mb-5 mb-lg-0">
                <div class="container-fluid px-5">
                    <div class="row gx-5">
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                               
                                <h3 class="font-alt">@Localizer["DeviceMockups"]</h3>
                                <p class="text-muted mb-0">@Localizer["ReadyToUseMockups"]</p>
                            </div>
                        </div>
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                                
                                <h3 class="font-alt">@Localizer["FlexibleUse"]</h3>
                                <p class="text-muted mb-0">@Localizer["PutAnythingOnScreen"]</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-5 mb-md-0">
                            <!-- Feature item-->
                            <div class="text-center">
                              
                                <h3 class="font-alt">@Localizer["FreeToUse"]</h3>
                                <p class="text-muted mb-0">@Localizer["ThemeFreeDownload"]</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <!-- Feature item-->
                            <div class="text-center">
                                
                                <h3 class="font-alt">@Localizer["OpenSource"]</h3>
                                <p class="text-muted mb-0">@Localizer["MITLicensed"]</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 order-lg-0">
                <!-- Features section device mockup-->
                <div class="features-device-mockup">
                    
                        <defs>
                            <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                <stop class="gradient-start-color" offset="0%"></stop>
                                <stop class="gradient-end-color" offset="100%"></stop>
                            </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="50"></circle>
                    </svg><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" xmlns="http://www.w3.org/2000/svg">
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect>
                    </svg><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"></circle></svg>
                    
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Basic features section-->
<section class="bg-light">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div class="col-12 col-lg-5">
                <h2 class="display-4 lh-1 mb-4">@Localizer["EnterNewAgeDesign"]</h2>
                <p class="lead fw-normal text-muted mb-5 mb-lg-0">@Localizer["ApplicationInformation"]</p>
            </div>
            <div class="col-sm-8 col-md-6">
                <div class="px-5 px-sm-0"><img class="img-fluid rounded-circle" src="https://source.unsplash.com/u8Jn2rzYIps/900x900" alt="..." /></div>
            </div>
        </div>
    </div>
</section>
<!-- Call to action section-->

<!-- App badge section-->
<section class="bg-gradient-primary-to-secondary" id="download">
    <div class="container px-5">
        <h2 class="text-center text-white font-alt mb-4">@Localizer["GetTheAppNow"]</h2>
        <div class="d-flex flex-column flex-lg-row align-items-center justify-content-center">
            <a class="me-lg-3 mb-4 mb-lg-0" href="#!"><img class="app-badge" src="assets/img/google-play-badge.svg" alt="..." /></a>
            <a href="#!"><img class="app-badge" src="assets/img/app-store-badge.svg" alt="..." /></a>
        </div>
    </div>
</section>
<!-- Footer-->
<footer class="bg-black text-center py-5">
    <div class="container px-5">
        <div class="text-white-50 small">
            <div class="mb-2">@Localizer["AllRightsReserved"]</div>
            <a href="#!">@Localizer["Privacy"]</a>
            <span class="mx-1">&middot;</span>
            <a href="#!">@Localizer["Terms"]</a>
            <span class="mx-1">&middot;</span>
            <a href="#!">@Localizer["FAQ"]</a>
        </div>
    </div>
</footer>
<!-- Feedback Modal-->
<div class="modal fade" id="feedbackModal" tabindex="-1" aria-labelledby="feedbackModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary-to-secondary p-4">
                <h5 class="modal-title font-alt text-white" id="feedbackModalLabel">@Localizer["SendFeedback"]</h5>
                <button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body border-0 p-4">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                        <label for="name">Full name</label>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                        <label for="email">Email address</label>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                        <label for="phone">Phone number</label>
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                        <label for="message">Message</label>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center mb-3">
                            <div class="fw-bolder">Form submission successful!</div>
                            To activate this form, sign up at
                            <br />
                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                    <!-- Submit Button-->
                    <div class="d-grid"><button class="btn btn-primary rounded-pill btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#submitButton").click(function (event) {
                event.preventDefault();

                var name = $("#name").val();
                var email = $("#email").val();
                var phone = $("#phone").val();
                var message = $("#message").val();

                var data = {
                    Name: name,
                    Email: email,
                    Phone: phone,
                    MessageText: message
                };

                $.ajax({
                    url: '@Url.Action("SendEmail", "Home")',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    success: function (response) {
                        // handle success
                        alert("Data sent successfully.");
                    },
                    error: function (error) {
                        // handle error
                        alert("Error sending data.");
                    }
                });
            });
        });
    </script>
    }

WebLabApp.web/Views/Shared/Components/Navbar/Default.cshtml
<div class="collapse navbar-collapse" id="navbarResponsive">
	<ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
		<li class="nav-item"><a class="nav-link me-lg-3" href="@Url.Action("Index","Home")">Home</a></li>
		<li class="nav-item"><a class="nav-link" href="@Url.Action("Index","File")">Files</a></li>
		<li class="nav-item"><a class="nav-link" href="@Url.Action("Validator","Validator")">Validator</a></li>
	</ul>
	<button class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">
		<span class="d-flex align-items-center">
			<svg class="bi" width="24" height="24" fill="blue">
				<use href="lib/bootstrap-icons/icons.svg#app"></use>
			</svg>
			<span class="small">Sign up for a course</span>
		</span>
	</button>
	@await Html.PartialAsync("_LanguageSwitcher")
</div>

WebLabApp.web/Views/Shared/_LanguageSwitcher.cshtml
<div>
    <a href="@Url.Action("SetLanguage", "Home", new { culture = "en-US", returnUrl = Context.Request.Path })">
        Eng
    </a>
    |
    <a href="@Url.Action("SetLanguage", "Home", new { culture = "uk-UA", returnUrl = Context.Request.Path })">
        Ua
    </a>
</div>

WebLabApp.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>New Age - Start Bootstrap Theme</title>
	<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

	<!-- Bootstrap icons-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
	<!-- Google fonts-->
	<link rel="preconnect" href="https://fonts.gstatic.com" />
	<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap" rel="stylesheet" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
	<!-- Navigation-->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
		<div class="container px-5">
			<a class="navbar-brand fw-bold" href="#page-top">Web IT School</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				Menu
				<i class="bi-list"></i>
			</button>
			@await Component.InvokeAsync("Navbar")
		</div>
	</nav>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - WebAppLab1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<!-- Core theme JS-->
	<script src="js/scripts.js"></script>
	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
	<!-- * *                               SB Forms JS                               * *-->
	<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
	<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebLabApp.web/Views/Validator/Validator.cshtml
@using WebLabApp.web.Models

@model ValidationModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>File Upload and Download</title>
</head>
<body>
</br>
</br>
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h1>Create</h1>
        </div>
        <div class="card-body">
            <form asp-action="Create">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Age"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Salary"></label>
                    <input asp-for="Salary" class="form-control" />
                    <span asp-validation-for="Salary" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Department"></label>
                    <input asp-for="Department" class="form-control" />
                    <span asp-validation-for="Department" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Role"></label>
                    <input asp-for="Role" class="form-control" />
                    <span asp-validation-for="Role" class="text-danger"></span>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary btn-lg mt-3">Create</button>
                </div>
            </form>
        </div>
    </div>



</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}